// This file was generated by Mendix Modeler.
//
// WARNING: Only the following code will be retained when actions are regenerated:
// - the import list
// - the code between BEGIN USER CODE and END USER CODE
// - the code between BEGIN EXTRA CODE and END EXTRA CODE
// Other code you write will be lost the next time you deploy the project.
// Special characters, e.g., é, ö, à, etc. are supported in comments.

package iprange.actions;

import com.mendix.core.Core;
import com.mendix.core.action.user.LoginAction;
import com.mendix.core.actionmanagement.ActionListener;
import com.mendix.systemwideinterfaces.core.IContext;
import com.mendix.webui.CustomJavaAction;
import iprange.IPRangeCheckerLoginAction;

public class ReplaceLoginAction extends CustomJavaAction<java.lang.Boolean>
{
	public ReplaceLoginAction(IContext context)
	{
		super(context);
	}

	@Override
	public java.lang.Boolean executeAction() throws Exception
	{
		// BEGIN USER CODE
		LoginActionListener loginActionListener = new LoginActionListener();
		loginActionListener.addReplaceEvent(IPRangeCheckerLoginAction.class.getName());
		Core.addUserAction(IPRangeCheckerLoginAction.class);
		Core.addListener(loginActionListener);
		
		return true;
		// END USER CODE
	}

	/**
	 * Returns a string representation of this action
	 */
	@Override
	public java.lang.String toString()
	{
		return "ReplaceLoginAction";
	}

	// BEGIN EXTRA CODE
	public class LoginActionListener extends ActionListener<LoginAction>
	{
		public LoginActionListener()
		{
			super(LoginAction.class);
		}

		@Override
		public boolean check(LoginAction action)
		{
			Core.addUserAction(IPRangeCheckerLoginAction.class);
			return true;
		}
	}
	// END EXTRA CODE
}
